# Site settings
title: "Konrad Tendera"
description: "A resume presenting in a clean way my LinkedIn profile."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Konrad Tendera"
resume_title:                   "Software Engineer"
resume_contact_email:
  "konradtendera@gmail.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/k0ner"
  resume_twitter_url:           "https://twitter.com/konradtendera"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/konradte"
  resume_linkedin_url:          "https://www.linkedin.com/in/konrad-tendera-40839255"
  resume_instagram_url:         "https://instagram.com/k0ner"
  resume_website_url:           "http://konradtendera.me"

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
